Fix not able to create Record with `id` attr
The constructor of Record prefers `id` to pass record ID, but it is not
possible to use this attr as the update function will set the record ID
to `id` property, which is readonly.

Not having this change will result in TypeError:

```
TypeError: Cannot set property id of #<Record> which has only a getter
```